sudo: false
cache:
  directories:
    - bundler

language: node_js

node_js:
  - "0.12"
  - "0.10"

script:
  - grunt test -v --stack -d
  # - true-cli "tests\specs\tests.scss"

before_install:
  - npm install -g grunt-cli bower
  - gem install bundler
  - bundle install

before_script:
  - npm install
  - bower install

matrix:
  fast_finish: true

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5c6b2c0566a68157128b
    on_success: change
    on_failure: always
    on_start: false
