sudo: false
cache: bundler

language: node_js

node_js:
  - "0.12"
  - "0.10"

script: grunt test -v --stack -d

before_install:
  - npm install -g grunt-cli bower
  - gem install bundler
  - bundle install

before_script:
  - npm install
  - bower install

# Gitter notifications
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aa7f671ba1a073e5a922
    on_success: change
    on_failure: always
    on_start: false
